name: conda

on:
  push:
    branches: [ master ]
    paths:
      - 'conda/**'
      - '.github/workflows/conda.yml'
  pull_request:
    paths:
      - 'conda/**'
      - '.github/workflows/conda.yml'

jobs:
  conda-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build-env
          auto-update-conda: true
          python-version: 3.11
          channels: conda-forge,defaults
      - name: Install conda-build
        shell: bash -l {0}
        run: conda install -y conda-build
      - name: Build recipe
        shell: bash -l {0}
        run: conda build conda
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-bld
          path: /usr/share/miniconda/conda-bld/**/*.tar.bz2
